### ISSUE TITLE
can not support select-search in  trace page  service 

### ISSUE THREAD

**Issue by zxbu** [apache/skywalking-ui#238]
![image](https://user-images.githubusercontent.com/32785355/56706129-6caa9100-6746-11e9-9164-a73659409370.png)

it would be better if service select can support select-search like this :

![image](https://user-images.githubusercontent.com/32785355/56706264-e2166180-6746-11e9-9e0e-573df0bc73e3.png)

**Comment by wu-sheng** [comment]
Please notice this, https://github.com/apache/skywalking/pull/2515

UI is going to be updated to RocketBot. I think there is search feature there. cc @TinyAllen
